### ISSUE TITLE
Questões diversas

### ISSUE THREAD

**Issue by victor-mrm** [Mysfer/mdbd#1]
Essa Issue foi feita para nós do Grupo do chat tirarmos duvidas com vcs
Grupo
Joao vitor
Vitão
Gabriel B
Lincoln
Barbara M
Wesley 
Lorrana

**Comment by jpfs2001** [comment]
Blz :+1:, qualquer duvida estamos aqui meu bom!

**Comment by victor-mrm** [comment]
nós também :+1:

**Comment by LincolnGomes** [comment]
5-Mostre quantas definições uma palavra tem em todos os dicionarios

Poderiam explicar melhor ?

**Comment by Paulo-Henrique-Schiavetti** [comment]
suponhamos que existam 5 dicionarios e em cada um deles tem uma linha para "amor" porém com definições diferentes, conte em quantos dicionários essa palavra apareceu.

**Comment by Paulo-Henrique-Schiavetti** [comment]
no caso a palavra amor:heart: teria aparecido 5 vezes nesse caso:heart::heart::heart::heart::heart:

**Comment by victor-mrm** [comment]
2- Mostre os sinônimos das palavras
É pra mostrar as palavras mesmo ou só o id delas ?

**Comment by victor-mrm** [comment]
@Mysfer  @LincolnGomes @Paulo-Henrique-Schiavetti  Garera responde eu na humilde

**Comment by victor-mrm** [comment]
![capturar](https://user-images.githubusercontent.com/32112540/31729129-e74e06ba-b40c-11e7-8430-cef4803832b0.PNG)

Garera mostrando apenas os sinônimos assim ta certo ?

**Comment by Paulo-Henrique-Schiavetti** [comment]
os sinonimos, os nomes, ta certo!

**Comment by Paulo-Henrique-Schiavetti** [comment]
espero que vocês tenham conseguido, desculpe a demora,:droplet::droplet:
